name: ppdiff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.4.0=h27087fc_1
  - blas=2.305=mkl
  - blas-devel=3.11.0=5_hcf00494_mkl
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.9.79=1
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.9.79=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.9.88=1
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.9.79=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.9.79=1
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.9.79=1
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-version=12.9=3
  - cuda-visual-tools=11.6.1=0
  - dbus=1.16.2=h24cb091_1
  - expat=2.7.3=hecca717_0
  - ffmpeg=5.1.0=gpl_h45a1190_101
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - gds-tools=1.14.1.1=4
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.6=he274497_3
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h5875eb1_mkl
  - libcblas=3.11.0=5_hfef963f_mkl
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.14.1.1=4
  - libcufile-dev=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.125=hb03c661_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - liblapack=3.11.0=5_h5e43f62_mkl
  - liblapacke=3.11.0=5_hdba1596_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libsqlite=3.51.2=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.3=h5347b49_0
  - libva=2.18.0=h0b41bf4_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - mkl=2025.3.0=h0e700b2_463
  - mkl-devel=2025.3.0=ha770c72_463
  - mkl-include=2025.3.0=hf2ce2f3_463
  - ncurses=6.5=h2d0b736_3
  - nettle=3.8.1=hc379101_1
  - nsight-compute=2025.2.0.11=0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - openh264=2.3.0=h27087fc_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.47=haa7fec5_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python_abi=3.9=8_cp39
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=pyhff2d567_0
  - svt-av1=1.2.0=h27087fc_0
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_hd72426e_102
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - antlr4-python3-runtime==4.8
      - bitarray==3.8.0
      - cython==3.2.4
      - hydra-core==1.1.1
      - joblib==1.5.3
      - numpy==1.22.4
      - omegaconf==2.1.1
      - packaging==25.0
      - portalocker==2.0.0
      - pyyaml==6.0.3
      - regex==2025.11.3
      - sacrebleu==1.5.1
      - scikit-learn==1.2.1
      - threadpoolctl==3.6.0
      - torch==1.13.1+cu116
      - torch-scatter==2.1.0+pt113cu116
      - torchaudio==0.13.1+cu116
      - torchvision==0.14.1+cu116
      - tqdm==4.64.1
prefix: /usr/local/envs/ppdiff
